import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Jakes Portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{/* //TODO Header */}
			<Header />

			{/* //TODO Hero */}

			{/* //TODO About */}

			{/* //TODO Experience */}

			{/* //TODO Skills */}

			{/* //TODO Experience */}

			{/* //TODO Projects */}

			{/* //TODO Contact Me */}
		</div>
	);
};

export default Home;
